### ISSUE TITLE
Is this posible to get options by sheet?

### ISSUE THREAD

**Issue by mandaputtra** [stevelacy/exceljs-transform-stream#2]
I had many worksheet on my excel it is possible to read only specific sheed?

**Comment by mandaputtra** [comment]
dont worry i just fork it. will contribute later thanks

**Comment by contra** [comment]
@mandaputtra FYI this feature shipped. This repo has moved and the package has a new name - https://github.com/staeco/xlsx-parse-stream

You can use the `selector` option to do this
