### ISSUE TITLE
Ability to read from the sheet name provided in opts as parameter

### ISSUE THREAD

**Issue by manisuec** [stevelacy/exceljs-transform-stream#3]
Current behaviour: It reads from all the sheets present in the workbook.

Expected behaviour: If a parameter say 'sheetName' is provided in opts; then read values only from the sheet with the given name.

Use Case: Most of the times, we are using one sheet say 'Sheet A' to provide instructions how to fill values in the next sheet say 'Sheet B'. So, relevant sheet to read values in that case is 'Sheet B'.

**Comment by contra** [comment]
@manisuec Should be pretty simple to do - I'm working on a rewrite of this package right now and can include this in that version

**Comment by contra** [comment]
@manisuec This shipped - you can use the `selector` option to do this.

**Comment by contra** [comment]
Also just an FYI this package moved and has a new name: https://github.com/staeco/xlsx-parse-stream
